pub mod ai;
pub mod gates;
pub mod grid;
pub mod grid_bot;
pub mod grid_executor;
mod interval;
pub mod pairs;
pub mod registry;
pub mod stat_arb;
pub mod strategy;

pub use ai::AiStrategy;
pub use gates::*;
pub use grid::{GridLevel, GridState, GridStrategy, OrderSide};
pub use grid_bot::{GridBot, GridBotConfig};
pub use grid_executor::{GridExecutor, GridOrderResult, RebalanceResult};
pub use interval::IntervalStrategy;
pub use pairs::{PairAction, PairConfig, PairSignal, PairsTrader};
pub use registry::StrategyRegistry;
pub use stat_arb::{StatArbConfig, StatArbSignal, StatisticalArbitrage};
pub use strategy::Strategy;
