[package]
name = "trader-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
t-invest-sdk = { git = "https://github.com/artemevsevev/t-invest-sdk.git", version = "0.6.0"}
tokio = { version = "1.42.0", features = ["full"] }
flume = "0.11.1"
anyhow = "1.0.95"
serde = { version = "1.0.219", features = ["derive"] }
tonic = "0.13.0"
# https://github.com/modelcontextprotocol/rust-sdk
rmcp = { version = "0.1", features = ["client"] }